#!/bin/sh
set -e

# Use the binary numbers in your diagnostic report to calculate the gamma
# rate and epsilon rate, then multiply them together. What is the power
# consumption of the submarine? (Be sure to represent your answer in
# decimal, not binary.)

{ echo "ibase=2"
  sed -f split_chars.sed \
    | awk -v OFS=" * " -f decode_rates.awk
} | bc
