#!/bin/sh
set -e
source decode_rating.sh

# Use the binary numbers in your diagnostic report to calculate the oxygen
# generator rating and CO2 scrubber rating, then multiply them together.
# What is the life support rating of the submarine? (Be sure to represent
# your answer in decimal, not binary.)

FILE="${TMPDIR%/}/input.$$"
trap 'rm -f "$FILE"' EXIT
cat >"$FILE"

oxygen_generator_rating="$(decode_rating 1 <"$FILE")"
co2_scrubber_rating="$(decode_rating 0 <"$FILE")"

{ echo "ibase=2"
  echo "$oxygen_generator_rating * $co2_scrubber_rating"
} | bc
