#!/bin/sh
set -e

# Figure out which board will win last. Once it wins, what would its final
# score be?

DIR="${TMPDIR%/}/solve.$$"
SIZE=5

trap 'rm -fr "$DIR"' EXIT
rm -fr "$DIR"
mkdir -p "$DIR/bingo"

read -r numbers
read -r
cat >"$DIR/boards"

IFS=,
for number in $numbers; do
  awk -f ../score_boards.awk -v size="$SIZE" -v number="$number" "$DIR/boards" \
    | tee "$DIR/boards.1" \
    | grep -E '^[0-9]+!?$' >"$DIR/scores"

  index=0
  while read -r line; do
    index=$((index+1))
    score="${line%!}"

    if [ "$score" != "$line" ]; then
      file="$DIR/bingo/$index"
      if ! [ -f "$file" ]; then
        echo $((number * score))
        touch "$file"
      fi
    fi
  done <"$DIR/scores"

  mv "$DIR/boards.1" "$DIR/boards"
done \
  | tail -n 1
