#!/bin/sh
set -e

# Determine the horizontal position that the crabs can align to using the
# least fuel possible so they can make you an escape route! How much fuel
# must they spend to align to that position?

awk -v FS=, -f ../fuel_usage.awk -f cost.awk \
  | sort -n \
  | head -n 1
