#!/bin/sh
set -e

# Calculate the horizontal position and depth you would have after
# following the planned course. What do you get if you multiply your final
# horizontal position by your final depth?

{ awk -f translate.awk
  echo "x * y"
} | bc
