#!/bin/sh
set -e

# Find a way to simulate lanternfish. How many lanternfish would there be
# after 80 days?

sed -f ../split_fish.sed \
  | awk -f ../translate_fish.awk -v n=80 \
  | bc ../simulate_fish.bc
