#!/bin/sh
set -e

# For each entry, determine all of the wire/segment connections and decode
# the four-digit output values. What do you get if you add up all of the
# output values?

awk -f decode_and_sum_values.awk
